SOURCE: CT
TARGET: MR
NUM_WORKERS: 4
FULLY_SUPERVISED: False
TRAIN:
  DA_METHOD: MPSCL
  MODEL: DeepLabv2
  RESTORE_FROM:   ../pretrained_model/training/ct2mr_model_pretrained.pth
  D_AUX_RESTORE:  ../pretrained_model/training/ct2mr_model_pretrained_D_aux.pth
  D_MAIN_RESTORE: ../pretrained_model/training/ct2mr_model_pretrained_D_main.pth
  CLASS_CENTER_FEA_INIT: ../pretrained_model/training/ct2mr_class_center_feas_init.npy
  D_TYPE:         PatchGAN
  D_NORM:          Batch_Norm
  MULTI_LEVEL: True
  LAMBDA_ADV_MAIN:      0.003
  LAMBDA_ADV_AUX:       0.00002
  LAMBDA_MPCL_SRC:       1.0
  LAMBDA_MPCL_TRG:       0.1
  CLASS_CENTER_M:       0.2
  PIXEL_SEL_TH:  0.25

  SRC_TEMP:      2.0
  SRC_BASE_TEMP: 1.0
  TRG_TEMP:      1.0
  TRG_BASE_TEMP: 1.0
  SRC_MARGIN:    0.2
  TRG_MARGIN:    0.2

  LAMBDA_DICE_SRC_MAIN:   1.0
  LAMBDA_DICE_SRC_AUX:    0.1

TEST:
  MODE: best

